version: '3'

services:
  pinvest:
    build:
      context: .
      dockerfile: Dockerfile
    image: pinvest
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '81:81'
    depends_on:
      - pinvest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
