version: '3'

services:
  pinvest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=0.0.1-RELEASE
    image: redyputras/pinvest:0.0.3-RELEASE
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '81:81'
    depends_on:
      - pinvest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
