version: '3'

services:
  pinvest:
    build: .  # Build image dari Dockerfile yang ada di direktori lokal
    ports:
      - "3000:3000"  # Map port 3000 di container ke port 3000 di host
    networks:
      - app-network  # Menghubungkan ke jaringan 'app-network'
      
networks:
  app-network:
    driver: bridge
