FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Salin sertifikat dari direktori build konteks ke dalam container
COPY certs/ /etc/letsencrypt/live/fine-streets-cut-quietly.a276.dcdg.xyz/

# Set izin yang tepat
RUN chmod -R 644 /etc/letsencrypt/live/fine-streets-cut-quietly.a276.dcdg.xyz/

EXPOSE 81 443
